// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDkXnWv5cdRRVNxt9JKfJbNDmq8LDAsbl4',
    appId: '1:390396524296:web:4e2118180d5ee7d0755ebd',
    messagingSenderId: '390396524296',
    projectId: 'livenotes-bbfba',
    authDomain: 'livenotes-bbfba.firebaseapp.com',
    storageBucket: 'livenotes-bbfba.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDnAI7QPYEK6mpfADdqAcYFnw1VnN5MIAI',
    appId: '1:390396524296:android:fa4817f18ad0c9ec755ebd',
    messagingSenderId: '390396524296',
    projectId: 'livenotes-bbfba',
    storageBucket: 'livenotes-bbfba.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCTZsP44WCkV3LzOmyiaflu_diE_YYb66E',
    appId: '1:390396524296:ios:fd12536f07db7975755ebd',
    messagingSenderId: '390396524296',
    projectId: 'livenotes-bbfba',
    storageBucket: 'livenotes-bbfba.firebasestorage.app',
    iosBundleId: 'com.example.liveNotes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCTZsP44WCkV3LzOmyiaflu_diE_YYb66E',
    appId: '1:390396524296:ios:fd12536f07db7975755ebd',
    messagingSenderId: '390396524296',
    projectId: 'livenotes-bbfba',
    storageBucket: 'livenotes-bbfba.firebasestorage.app',
    iosBundleId: 'com.example.liveNotes',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDkXnWv5cdRRVNxt9JKfJbNDmq8LDAsbl4',
    appId: '1:390396524296:web:09938b76441559c7755ebd',
    messagingSenderId: '390396524296',
    projectId: 'livenotes-bbfba',
    authDomain: 'livenotes-bbfba.firebaseapp.com',
    storageBucket: 'livenotes-bbfba.firebasestorage.app',
  );
}
